[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
conditional_stocks = "8S7LwM6yRszZaAoEQqgE1AYcZJLpyVVC5MRr7vqCxLtg"

[programs.devnet]
conditional_stocks = "8S7LwM6yRszZaAoEQqgE1AYcZJLpyVVC5MRr7vqCxLtg"

[provider]
cluster = "Localnet"
wallet = ".local/admin.json"

[scripts]
test = "bun run test:solana"
