[toolchain]
anchor_version = "1.1.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
conditional_stocks = "53gtyz9nYzS7vwSbx2v7GeGLrMTas7vCATkjiKvAG1ra"

[programs.devnet]
conditional_stocks = "53gtyz9nYzS7vwSbx2v7GeGLrMTas7vCATkjiKvAG1ra"

[provider]
cluster = "Localnet"
wallet = ".local/admin.json"

[scripts]
test = "bun run test:solana"
