import { resolve } from "node:path";

const contractNames = [
  "ConditionalExchange",
  "ConditionalSettlement",
  "AtomicOrderRouter",
  "ManualResolutionController",
  "MarketRegistry",
  "OrderRecoveryRouter",
  "OrderValidator",
  "PositionRouter",
  "ProtocolAuthority",
  "ProtocolFeeVault",
  "PayoutVault",
] as const;

const externalArtifacts = [
  {
    identifier: "conditionalTokensAbi",
    path: "../../contracts/node_modules/@gnosis.pm/conditional-tokens-contracts/build/contracts/ConditionalTokens.json",
  },
] as const;

const toIdentifier = (name: string): string => `${name[0]?.toLowerCase() ?? ""}${name.slice(1)}Abi`;

const generated: string[] = [
  "// This file is generated by scripts/generate.ts. Do not edit manually.",
  "",
];

for (const contractName of contractNames) {
  const artifactPath = resolve(
    import.meta.dir,
    `../../contracts/out/${contractName}.sol/${contractName}.json`,
  );
  const artifact = (await Bun.file(artifactPath).json()) as { abi?: unknown };
  if (!Array.isArray(artifact.abi)) {
    throw new Error(`Missing ABI in ${artifactPath}`);
  }
  generated.push(
    `export const ${toIdentifier(contractName)} = ${JSON.stringify(artifact.abi, null, 2)} as const;`,
    "",
  );
}

for (const artifact of externalArtifacts) {
  const artifactPath = resolve(import.meta.dir, artifact.path);
  const contents = (await Bun.file(artifactPath).json()) as { abi?: unknown };
  if (!Array.isArray(contents.abi)) {
    throw new Error(`Missing ABI in ${artifactPath}`);
  }
  generated.push(
    `export const ${artifact.identifier} = ${JSON.stringify(contents.abi, null, 2)} as const;`,
    "",
  );
}

await Bun.write(resolve(import.meta.dir, "../src/generated.ts"), `${generated.join("\n")}\n`);
