[Unit]
Wants=network-online.target
After=network-online.target

[Service]
UMask=0077
LimitNOFILE=65536
LimitCORE=0
TasksMax=512
MemoryAccounting=true
MemoryHigh=3G
MemoryMax=3200M
TimeoutStopSec=120s
Restart=on-failure
RestartSec=10s
